version: "3"
services:

  backend:
    image: tower-backend
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    volumes:
      - $PWD:/work
    working_dir: /work
    environment:
        # From https://github.com/seqeralabs/nf-tower/issues/249#issuecomment-1028170612
        TOWER_SMTP_USER: richel
        TOWER_SMTP_PASSWORD: iloverichel
        TOWER_SMTP_HOST: smtp.richelbilderbeek.nl
        TOWER_CONTACT_EMAIL: richel@richelbilderbeek.nl

  frontend:
    build: ./tower-web
    networks:
      - frontend
    ports:
      - 8000:80
    depends_on:
      - backend

networks:
  frontend: {}
  backend: {}
